SELECT TOP(1)
(SELECT (MAX(_MAX)-MIN(_MIN)) AS COBBLES FROM [iba_db].[dbo].[VIEW_IBA_DAT] WHERE _NAME = 'MILL - ROLLED COUNT' AND YEAR(_TimeStamp) = YEAR(GETDATE()) AND MONTH(_TimeStamp) = MONTH(GETDATE()) AND DAY(_TimeStamp) = DAY(GETDATE())) as ROLLED,
(SELECT (MAX(_MAX)-MIN(_MIN)) AS COBBLES FROM [iba_db].[dbo].[VIEW_IBA_DAT] WHERE _NAME = 'MILL - COBBLE COUNT' AND YEAR(_TimeStamp) = YEAR(GETDATE()) AND MONTH(_TimeStamp) = MONTH(GETDATE()) AND DAY(_TimeStamp) = DAY(GETDATE())) as COBBLES
FROM [iba_db].[dbo].[VIEW_IBA_DAT] WHERE YEAR(_TimeStamp) = YEAR(GETDATE()) AND MONTH(_TimeStamp) = MONTH(GETDATE()) AND DAY(_TimeStamp) = DAY(GETDATE());
